[project]
name = 'Decentralized-Intern-Matching-System'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Decentralized-Intern-Matching-System]
path = 'contracts/Decentralized-Intern-Matching-System.clar'
clarity_version = 3
epoch = 3.1

[contracts.reputation-system]
path = 'contracts/reputation-system.clar'
clarity_version = 3
epoch = 3.1

[contracts.performance-tracker]
path = 'contracts/performance-tracker.clar'
clarity_version = 3
epoch = 3.1

[contracts.certificate-system]
path = 'contracts/certificate-system.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
